# Generated by Django 3.2.9 on 2022-02-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='type',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='subtype',
            new_name='subgroup',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='commercial_section',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='origin',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
