# Generated by Django 3.2.9 on 2022-05-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ingredient_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='presentation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
