# Generated by Django 3.2.9 on 2022-07-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_ingredient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cooking_type',
            field=models.CharField(default='hervido', max_length=50),
            preserve_default=False,
        ),
    ]
