# Generated by Django 4.0 on 2022-07-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_food_cooking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
