# Generated by Django 4.0 on 2022-07-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='atherosclerosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='cardiac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='celiac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='cetogenic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='diabetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='hypertensive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='kosher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='lactose_intolerant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='veggie',
            field=models.BooleanField(default=False),
        ),
    ]
