# Generated by Django 3.2.9 on 2022-02-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=50)),
                ('edible_ptc', models.FloatField(default=1.0)),
                ('density', models.FloatField()),
                ('unit_weight', models.FloatField()),
                ('price_per_gram', models.FloatField()),
                ('calories', models.FloatField()),
                ('proteins', models.FloatField()),
                ('water', models.FloatField(blank=True, null=True)),
                ('sugar', models.FloatField(blank=True, null=True)),
                ('starches', models.FloatField(blank=True, null=True)),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('total_carbohydrates', models.FloatField()),
                ('polyunsaturated_fats', models.FloatField(blank=True, null=True)),
                ('monounsaturated_fats', models.FloatField(blank=True, null=True)),
                ('saturated_fats', models.FloatField(blank=True, null=True)),
                ('trans_fats', models.FloatField(blank=True, null=True)),
                ('total_fats', models.FloatField()),
                ('total_cholesterol', models.FloatField(blank=True, null=True)),
                ('good_cholesterol_HDL', models.FloatField(blank=True, null=True)),
                ('bad_cholesterol_LDL', models.FloatField(blank=True, null=True)),
                ('vitamin_a', models.FloatField(blank=True, null=True)),
                ('vitamin_b1', models.FloatField(blank=True, null=True)),
                ('vitamin_b2', models.FloatField(blank=True, null=True)),
                ('vitamin_b3', models.FloatField(blank=True, null=True)),
                ('vitamin_b12', models.FloatField(blank=True, null=True)),
                ('vitamin_c', models.FloatField(blank=True, null=True)),
                ('vitamin_d', models.FloatField(blank=True, null=True)),
                ('vitamin_e', models.FloatField(blank=True, null=True)),
                ('vitamin_k', models.FloatField(blank=True, null=True)),
                ('total_vitamins', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField()),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('zinc', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('phosphorus', models.FloatField(blank=True, null=True)),
                ('magnesium', models.FloatField(blank=True, null=True)),
                ('total_minerals', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 's',
            },
        ),
    ]
