# Generated by Django 3.2.9 on 2022-02-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220227_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
